language: python

python:
  - 3.5

services: postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE direct_me;" -U postgres
  - python manage.py migrate

script:
  - python manage.py test