# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points_update_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
